name: COPR release

on:
  workflow_dispatch:

jobs:
  COPR_build:
    uses: pvermeer/rpm-tools/.github/workflows/copr-release.yml@main
    with:
      spec_file: ./steam-steamos.spec
      copr_owner: pvermeer
      copr_project: steam-steamos
      copr_package: steam-steamos
    permissions:
      contents: write
    secrets:
      COPR_WEBHOOK: ${{ secrets.COPR_WEBHOOK }}
